## config context path to "/" by setting an empty string
server:
  port: 8081
  error:
    whitelabel:
      enabled: false

logging:
  config: ${agens.spark.spark-home}/conf/log4j.properties
  level:
    root: warn

spring:
  pid:
    file: ${agens.product.name}.pid
  main:
    banner-mode: "off"
  resources:
    cache:
      period: 3600

agens:
  api:
    base-path: /api
    query-timeout: 600000       # 1000 ms = 1 sec
  elasticsearch:
    host: 192.168.0.30
    port: 9200
    username:
    password:
    page-size: 2500
    vertex-index: agensvertex
    edge-index: agensedge
  spark:
    app-name: es-bitnine
    spark-home: /home/bgmin/Servers/spark
    # master-uri: spark://192.168.0.30:7077
    master-uri: local
    extra-jars: jars/elasticsearch-hadoop-7.7.1.jar,jars/elasticsearch-spark-20_2.11-7.7.1.jar,jars/graphframes-0.8.0-spark2.4-s_2.11.jar
  product:
    name: agenspop-spark
    version: 0.0.1-dev
    hello-msg: agenspop-spark v1.0 (since 2019-10-01)